export enum GrupoMuscular {
    TRAPEZIO = 'TRAPÉZIO',
    DELTOIDE = 'DELTÓIDE',
    PEITORAL = 'PEITORAL',
    DORSAL = 'DORSAL',
    ISQUIOTIBIAL = 'ISQUIOTIBIAL',
    QUADRICEPS = 'QUADRÍCEPS',
    GLUTEO = 'GLÚTEO',
    BICEPS = 'BÍCEPS',
    TRICEPS = 'TRÍCEPS',
    ANTEBRACO = 'ANTEBRAÇO',
    PANTURRILHA = 'PANTURRILHA',
    ABDOMINAL = 'ABDOMINAL'
}